site_name: BEI API Documentation
site_url: https://docs.brighteyeintel.co.uk
theme:
  name: material
markdown_extensions:
  - tables
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting your API key: apikeys.md
  - Authentication: authentication.md
  - REST API:
    - Company: api/company.md
    - Crypto: api/crypto.md
    - Email: api/email.md
    - IP: api/ip.md
    - Macaddress: api/macaddress.md
    - Officers: api/officers.md
    - Phone: api/phone.md
    - URL: api/url.md
    - Username: api/username.md
    - VehicleReg: api/vehiclereg.md
    - Vinted: api/vinted.md
    - Vision: api/vision.md
  - Response Types:
    - Shared: types/shared.md
    - Company: types/company.md
    - Crypto: types/crypto.md
    - Email: types/email.md
    - IP: types/ip.md
    - Macaddress: types/bssid.md
    - Officers: types/officers.md
    - Phone: types/phone.md
    - URL: types/url.md
    - Username: types/username.md
    - VehicleReg: types/vehiclereg.md
    - Vinted: types/vinted.md
    - Vision: types/vision.md
